name: Deploy Backend

# Kích hoạt khi có push lên nhánh main
on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: self-hosted  # Sử dụng runner tự quản trên VPS
    environment: docker   # Đây là tùy chọn không bắt buộc
    steps:
    
    # Bước 1: Tải mã nguồn từ repository về VPS
    - name: Checkout code
      uses: actions/checkout@v2

    # Bước 2: Thiết lập Docker Compose và khởi động container backend
    - name: Build and Deploy Backend with Docker Compose
      run: |
        docker compose down    # Dừng các container cũ
        docker compose up --build -d  # Build và khởi động lại container
